version: "3.3"

services:
    app_backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app_backend
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app_backend
            SERVICE_TAGS: dev
        working_dir: /var/www
        ports:
            - "127.0.0.1:9000:9000"
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php/www.prod.conf:/usr/local/etc/php-fpm.d/www.conf
        networks:
            - app_network

    app_database:
        image: mysql:5.7
        container_name: app_database
        restart: unless-stopped
        tty: true
        command: --default-authentication-plugin=mysql_native_password
        env_file: ./.env.db
        ports:
            - "3306:3306"
        networks:
            - app_network

    app_nginx:
        image: nginx
        restart: unless-stopped
        tty: true
        container_name: app_nginx
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./:/var/www/
        ports:
            - "8081:80"
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
